import type { Metadata } from 'next'
import { BRAND, SITE_URL } from '@/lib/site'

/** Social card image — 1200×630, generated by the `app/og/route.tsx` route. */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 }
export const OG_IMAGE_ALT = `${BRAND} — szkoła wspinaczki na Jurze`

/** A fresh object per call — the Next metadata resolver consumes it. */
export const ogImage = () => ({
  url: `${SITE_URL}/og`,
  ...OG_IMAGE_SIZE,
  alt: OG_IMAGE_ALT,
})

/**
 * Page metadata: title, description, canonical and social card.
 *
 * The result is exported from page.tsx as `generateMetadata`, NOT as
 * `export const metadata` — the const form requires a literal, so a function
 * call will not compile inside it.
 *
 * Next merges metadata SHALLOWLY: a page's `openGraph` object replaces the
 * layout's entirely. Hence this helper — one source for the shape of the card,
 * instead of the full set of fields retyped on every page (and forgotten on one
 * of them).
 *
 * `canonical` fixes something the old site lacked altogether: the address with
 * and without "www" both answered 200 and Google had to guess which was
 * authoritative. A 301 redirect in nginx backs this up.
 */
export function pageMetadata({
  title,
  description,
  path,
}: {
  title: string
  description: string
  /** Root-relative path, e.g. "/kursy" — expanded with the domain by metadataBase. */
  path: string
}): Metadata {
  const fullTitle = `${title} | ${BRAND}`

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      siteName: BRAND,
      locale: 'pl_PL',
      url: path,
      title: fullTitle,
      description,
      images: [ogImage()],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [ogImage()],
    },
  }
}
